POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNoYWRvdyIsImlkIjoiNjUyMmViZmNjZjc5NGJjNDViMDljYmQ2IiwiaWF0IjoxNjk2ODY0NzA2fQ.-DwWh-lJlpiPxu96ZnAp_oPViBdS3m8EWhFzzNYuSLQ

{
  "title": "test",
  "author": "bloop",
  "url": "https://test.com/bloop",
  "userId": "6522ebfccf794bc45b09cbd6"
}
